services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    volumes:
      - ./db:/var/lib/postgresql/data

  holgerdanske:
    container_name: holgerdanske
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app

  prisma-studio:
    image: node:latest
    restart: always
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "npm install && npx prisma studio"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}"
    ports:
      - "127.0.0.1:5555:5555" # Change this line to match your configuration